repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: flake8
        args: [--config, .flake8]
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
      - id: reorder-python-imports
        args: [--application-directories=gaiaTiler]
  - repo: https://github.com/prettier/prettier
    rev: 1.18.2
    hooks:
      - id: prettier
        language_version: system
        exclude: .github/ISSUE_TEMPLATE/*
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.782"
    hooks:
      - id: mypy
